### ISSUE TITLE
Freezing main thread on iOS Safari

### ISSUE THREAD

**Issue by coreyward** [taion/scroll-behavior#130]
Using Gatsby v2, this library is causing an issue with scrolling in a container on iOS Safari in a particular situation.

```html
<div class="nav">
  <div class="item">Some content</div>
  <div class="item">Some content</div>
</div>
```
```css
body {
  position: fixed;
  overflow: hidden;
 }

.nav {
  position: fixed;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  overflow-y: auto;
  -webkit-overflow-scroll: touch; 
}
```

This is a fairly basic navigation overlay with scrolling content. Assuming the child elements are long enough, this should scroll up and down while the `<body>` remains fixed. 

It works generally, but if I'm at the top of the `.nav` element and try to scroll up further (swiping down, which would normally give you a peak above the document w/ the springboard animation), the page doesn't scroll at all and scrolling down (swiping up) immediately after is similarly “frozen”. After ~1s with no interaction the behavior resets and scrolling down (swiping up) works again. The same behavior occurs when at the bottom of the `.nav` container, only in reverse: scrolling down further (swiping up) causes the freeze. 

I checked out the timeline to observe and found that this method is getting called excessively during the periods where behavior is “frozen”, but not at all otherwise: 

https://github.com/taion/scroll-behavior/blob/4f6f2a57239c4a1825986304bd3d1479dbc35468/src/index.js#L146-L167

I suspect that this is somewhat expensive, and deferring the action using `requestAnimationFrame` is amplifying the problem, locking the main thread. I'm not sure what the intent is for this code, and as such, I'm not sure the best course of action to mitigate the issue.
